// As espécies que existem no POKÉMON GLITCH EDITION: os 151 de Kanto, as que
// vazam de fora dele (iniciais, eras, formas regionais, os PIKACHU de boné, o
// ??????????) e o MISSINGNO., que não está em tabela nenhuma e não tem arquivo
// de sprite — o desenho dele é feito em código, aqui e no jogo.
// `sprite` é o arquivo em assets/sprites/pokemon/ quando não é o nº da Pokédex.
// Gerado a partir de src/data/ (tools/gera_especies.py). Não edite à mão.
export const ESPECIES = [
{"id": "bulbasaur","dex": 1,"nome": "BULBASAUR","tipos": ["PLANTA","VENENO"]},
{"id": "ivysaur","dex": 2,"nome": "IVYSAUR","tipos": ["PLANTA","VENENO"]},
{"id": "venusaur","dex": 3,"nome": "VENUSAUR","tipos": ["PLANTA","VENENO"]},
{"id": "charmander","dex": 4,"nome": "CHARMANDER","tipos": ["FOGO"]},
{"id": "charmeleon","dex": 5,"nome": "CHARMELEON","tipos": ["FOGO"]},
{"id": "charizard","dex": 6,"nome": "CHARIZARD","tipos": ["FOGO","VOADOR"]},
{"id": "squirtle","dex": 7,"nome": "SQUIRTLE","tipos": ["ÁGUA"]},
{"id": "wartortle","dex": 8,"nome": "WARTORTLE","tipos": ["ÁGUA"]},
{"id": "blastoise","dex": 9,"nome": "BLASTOISE","tipos": ["ÁGUA"]},
{"id": "caterpie","dex": 10,"nome": "CATERPIE","tipos": ["INSETO"]},
{"id": "metapod","dex": 11,"nome": "METAPOD","tipos": ["INSETO"]},
{"id": "butterfree","dex": 12,"nome": "BUTTERFREE","tipos": ["INSETO","VOADOR"]},
{"id": "weedle","dex": 13,"nome": "WEEDLE","tipos": ["INSETO","VENENO"]},
{"id": "kakuna","dex": 14,"nome": "KAKUNA","tipos": ["INSETO","VENENO"]},
{"id": "beedrill","dex": 15,"nome": "BEEDRILL","tipos": ["INSETO","VENENO"]},
{"id": "pidgey","dex": 16,"nome": "PIDGEY","tipos": ["NORMAL","VOADOR"]},
{"id": "pidgeotto","dex": 17,"nome": "PIDGEOTTO","tipos": ["NORMAL","VOADOR"]},
{"id": "pidgeot","dex": 18,"nome": "PIDGEOT","tipos": ["NORMAL","VOADOR"]},
{"id": "rattata","dex": 19,"nome": "RATTATA","tipos": ["NORMAL"]},
{"id": "raticate","dex": 20,"nome": "RATICATE","tipos": ["NORMAL"]},
{"id": "spearow","dex": 21,"nome": "SPEAROW","tipos": ["NORMAL","VOADOR"]},
{"id": "fearow","dex": 22,"nome": "FEAROW","tipos": ["NORMAL","VOADOR"]},
{"id": "ekans","dex": 23,"nome": "EKANS","tipos": ["VENENO"]},
{"id": "arbok","dex": 24,"nome": "ARBOK","tipos": ["VENENO"]},
{"id": "pikachu","dex": 25,"nome": "PIKACHU","tipos": ["ELÉTRICO"]},
{"id": "raichu","dex": 26,"nome": "RAICHU","tipos": ["ELÉTRICO"]},
{"id": "sandshrew","dex": 27,"nome": "SANDSHREW","tipos": ["TERRA"]},
{"id": "sandslash","dex": 28,"nome": "SANDSLASH","tipos": ["TERRA"]},
{"id": "nidoranf","dex": 29,"nome": "NIDORAN-F","tipos": ["VENENO"]},
{"id": "nidorina","dex": 30,"nome": "NIDORINA","tipos": ["VENENO"]},
{"id": "nidoqueen","dex": 31,"nome": "NIDOQUEEN","tipos": ["VENENO","TERRA"]},
{"id": "nidoranm","dex": 32,"nome": "NIDORAN-M","tipos": ["VENENO"]},
{"id": "nidorino","dex": 33,"nome": "NIDORINO","tipos": ["VENENO"]},
{"id": "nidoking","dex": 34,"nome": "NIDOKING","tipos": ["VENENO","TERRA"]},
{"id": "clefairy","dex": 35,"nome": "CLEFAIRY","tipos": ["NORMAL"]},
{"id": "clefable","dex": 36,"nome": "CLEFABLE","tipos": ["NORMAL"]},
{"id": "vulpix","dex": 37,"nome": "VULPIX","tipos": ["FOGO"]},
{"id": "ninetales","dex": 38,"nome": "NINETALES","tipos": ["FOGO"]},
{"id": "jigglypuff","dex": 39,"nome": "JIGGLYPUFF","tipos": ["NORMAL"]},
{"id": "wigglytuff","dex": 40,"nome": "WIGGLYTUFF","tipos": ["NORMAL"]},
{"id": "zubat","dex": 41,"nome": "ZUBAT","tipos": ["VENENO","VOADOR"]},
{"id": "golbat","dex": 42,"nome": "GOLBAT","tipos": ["VENENO","VOADOR"]},
{"id": "oddish","dex": 43,"nome": "ODDISH","tipos": ["PLANTA","VENENO"]},
{"id": "gloom","dex": 44,"nome": "GLOOM","tipos": ["PLANTA","VENENO"]},
{"id": "vileplume","dex": 45,"nome": "VILEPLUME","tipos": ["PLANTA","VENENO"]},
{"id": "paras","dex": 46,"nome": "PARAS","tipos": ["INSETO","PLANTA"]},
{"id": "parasect","dex": 47,"nome": "PARASECT","tipos": ["INSETO","PLANTA"]},
{"id": "venonat","dex": 48,"nome": "VENONAT","tipos": ["INSETO","VENENO"]},
{"id": "venomoth","dex": 49,"nome": "VENOMOTH","tipos": ["INSETO","VENENO"]},
{"id": "diglett","dex": 50,"nome": "DIGLETT","tipos": ["TERRA"]},
{"id": "dugtrio","dex": 51,"nome": "DUGTRIO","tipos": ["TERRA"]},
{"id": "meowth","dex": 52,"nome": "MEOWTH","tipos": ["NORMAL"]},
{"id": "persian","dex": 53,"nome": "PERSIAN","tipos": ["NORMAL"]},
{"id": "psyduck","dex": 54,"nome": "PSYDUCK","tipos": ["ÁGUA"]},
{"id": "golduck","dex": 55,"nome": "GOLDUCK","tipos": ["ÁGUA"]},
{"id": "mankey","dex": 56,"nome": "MANKEY","tipos": ["LUTADOR"]},
{"id": "primeape","dex": 57,"nome": "PRIMEAPE","tipos": ["LUTADOR"]},
{"id": "growlithe","dex": 58,"nome": "GROWLITHE","tipos": ["FOGO"]},
{"id": "arcanine","dex": 59,"nome": "ARCANINE","tipos": ["FOGO"]},
{"id": "poliwag","dex": 60,"nome": "POLIWAG","tipos": ["ÁGUA"]},
{"id": "poliwhirl","dex": 61,"nome": "POLIWHIRL","tipos": ["ÁGUA"]},
{"id": "poliwrath","dex": 62,"nome": "POLIWRATH","tipos": ["ÁGUA","LUTADOR"]},
{"id": "abra","dex": 63,"nome": "ABRA","tipos": ["PSÍQUICO"]},
{"id": "kadabra","dex": 64,"nome": "KADABRA","tipos": ["PSÍQUICO"]},
{"id": "alakazam","dex": 65,"nome": "ALAKAZAM","tipos": ["PSÍQUICO"]},
{"id": "machop","dex": 66,"nome": "MACHOP","tipos": ["LUTADOR"]},
{"id": "machoke","dex": 67,"nome": "MACHOKE","tipos": ["LUTADOR"]},
{"id": "machamp","dex": 68,"nome": "MACHAMP","tipos": ["LUTADOR"]},
{"id": "bellsprout","dex": 69,"nome": "BELLSPROUT","tipos": ["PLANTA","VENENO"]},
{"id": "weepinbell","dex": 70,"nome": "WEEPINBELL","tipos": ["PLANTA","VENENO"]},
{"id": "victreebel","dex": 71,"nome": "VICTREEBEL","tipos": ["PLANTA","VENENO"]},
{"id": "tentacool","dex": 72,"nome": "TENTACOOL","tipos": ["ÁGUA","VENENO"]},
{"id": "tentacruel","dex": 73,"nome": "TENTACRUEL","tipos": ["ÁGUA","VENENO"]},
{"id": "geodude","dex": 74,"nome": "GEODUDE","tipos": ["PEDRA","TERRA"]},
{"id": "graveler","dex": 75,"nome": "GRAVELER","tipos": ["PEDRA","TERRA"]},
{"id": "golem","dex": 76,"nome": "GOLEM","tipos": ["PEDRA","TERRA"]},
{"id": "ponyta","dex": 77,"nome": "PONYTA","tipos": ["FOGO"]},
{"id": "rapidash","dex": 78,"nome": "RAPIDASH","tipos": ["FOGO"]},
{"id": "slowpoke","dex": 79,"nome": "SLOWPOKE","tipos": ["ÁGUA","PSÍQUICO"]},
{"id": "slowbro","dex": 80,"nome": "SLOWBRO","tipos": ["ÁGUA","PSÍQUICO"]},
{"id": "magnemite","dex": 81,"nome": "MAGNEMITE","tipos": ["ELÉTRICO","AÇO"]},
{"id": "magneton","dex": 82,"nome": "MAGNETON","tipos": ["ELÉTRICO","AÇO"]},
{"id": "farfetchd","dex": 83,"nome": "FARFETCHD","tipos": ["NORMAL","VOADOR"]},
{"id": "doduo","dex": 84,"nome": "DODUO","tipos": ["NORMAL","VOADOR"]},
{"id": "dodrio","dex": 85,"nome": "DODRIO","tipos": ["NORMAL","VOADOR"]},
{"id": "seel","dex": 86,"nome": "SEEL","tipos": ["ÁGUA"]},
{"id": "dewgong","dex": 87,"nome": "DEWGONG","tipos": ["ÁGUA","GELO"]},
{"id": "grimer","dex": 88,"nome": "GRIMER","tipos": ["VENENO"]},
{"id": "muk","dex": 89,"nome": "MUK","tipos": ["VENENO"]},
{"id": "shellder","dex": 90,"nome": "SHELLDER","tipos": ["ÁGUA"]},
{"id": "cloyster","dex": 91,"nome": "CLOYSTER","tipos": ["ÁGUA","GELO"]},
{"id": "gastly","dex": 92,"nome": "GASTLY","tipos": ["FANTASMA","VENENO"]},
{"id": "haunter","dex": 93,"nome": "HAUNTER","tipos": ["FANTASMA","VENENO"]},
{"id": "gengar","dex": 94,"nome": "GENGAR","tipos": ["FANTASMA","VENENO"]},
{"id": "onix","dex": 95,"nome": "ONIX","tipos": ["PEDRA","TERRA"]},
{"id": "drowzee","dex": 96,"nome": "DROWZEE","tipos": ["PSÍQUICO"]},
{"id": "hypno","dex": 97,"nome": "HYPNO","tipos": ["PSÍQUICO"]},
{"id": "krabby","dex": 98,"nome": "KRABBY","tipos": ["ÁGUA"]},
{"id": "kingler","dex": 99,"nome": "KINGLER","tipos": ["ÁGUA"]},
{"id": "voltorb","dex": 100,"nome": "VOLTORB","tipos": ["ELÉTRICO"]},
{"id": "electrode","dex": 101,"nome": "ELECTRODE","tipos": ["ELÉTRICO"]},
{"id": "exeggcute","dex": 102,"nome": "EXEGGCUTE","tipos": ["PLANTA","PSÍQUICO"]},
{"id": "exeggutor","dex": 103,"nome": "EXEGGUTOR","tipos": ["PLANTA","PSÍQUICO"]},
{"id": "cubone","dex": 104,"nome": "CUBONE","tipos": ["TERRA"]},
{"id": "marowak","dex": 105,"nome": "MAROWAK","tipos": ["TERRA"]},
{"id": "hitmonlee","dex": 106,"nome": "HITMONLEE","tipos": ["LUTADOR"]},
{"id": "hitmonchan","dex": 107,"nome": "HITMONCHAN","tipos": ["LUTADOR"]},
{"id": "lickitung","dex": 108,"nome": "LICKITUNG","tipos": ["NORMAL"]},
{"id": "koffing","dex": 109,"nome": "KOFFING","tipos": ["VENENO"]},
{"id": "weezing","dex": 110,"nome": "WEEZING","tipos": ["VENENO"]},
{"id": "rhyhorn","dex": 111,"nome": "RHYHORN","tipos": ["TERRA","PEDRA"]},
{"id": "rhydon","dex": 112,"nome": "RHYDON","tipos": ["TERRA","PEDRA"]},
{"id": "chansey","dex": 113,"nome": "CHANSEY","tipos": ["NORMAL"]},
{"id": "tangela","dex": 114,"nome": "TANGELA","tipos": ["PLANTA"]},
{"id": "kangaskhan","dex": 115,"nome": "KANGASKHAN","tipos": ["NORMAL"]},
{"id": "horsea","dex": 116,"nome": "HORSEA","tipos": ["ÁGUA"]},
{"id": "seadra","dex": 117,"nome": "SEADRA","tipos": ["ÁGUA"]},
{"id": "goldeen","dex": 118,"nome": "GOLDEEN","tipos": ["ÁGUA"]},
{"id": "seaking","dex": 119,"nome": "SEAKING","tipos": ["ÁGUA"]},
{"id": "staryu","dex": 120,"nome": "STARYU","tipos": ["ÁGUA"]},
{"id": "starmie","dex": 121,"nome": "STARMIE","tipos": ["ÁGUA","PSÍQUICO"]},
{"id": "mrmime","dex": 122,"nome": "MR-MIME","tipos": ["PSÍQUICO"]},
{"id": "scyther","dex": 123,"nome": "SCYTHER","tipos": ["INSETO","VOADOR"]},
{"id": "jynx","dex": 124,"nome": "JYNX","tipos": ["GELO","PSÍQUICO"]},
{"id": "electabuzz","dex": 125,"nome": "ELECTABUZZ","tipos": ["ELÉTRICO"]},
{"id": "magmar","dex": 126,"nome": "MAGMAR","tipos": ["FOGO"]},
{"id": "pinsir","dex": 127,"nome": "PINSIR","tipos": ["INSETO"]},
{"id": "tauros","dex": 128,"nome": "TAUROS","tipos": ["NORMAL"]},
{"id": "magikarp","dex": 129,"nome": "MAGIKARP","tipos": ["ÁGUA"]},
{"id": "gyarados","dex": 130,"nome": "GYARADOS","tipos": ["ÁGUA","VOADOR"]},
{"id": "lapras","dex": 131,"nome": "LAPRAS","tipos": ["ÁGUA","GELO"]},
{"id": "ditto","dex": 132,"nome": "DITTO","tipos": ["NORMAL"]},
{"id": "eevee","dex": 133,"nome": "EEVEE","tipos": ["NORMAL"]},
{"id": "vaporeon","dex": 134,"nome": "VAPOREON","tipos": ["ÁGUA"]},
{"id": "jolteon","dex": 135,"nome": "JOLTEON","tipos": ["ELÉTRICO"]},
{"id": "flareon","dex": 136,"nome": "FLAREON","tipos": ["FOGO"]},
{"id": "porygon","dex": 137,"nome": "PORYGON","tipos": ["NORMAL"]},
{"id": "omanyte","dex": 138,"nome": "OMANYTE","tipos": ["PEDRA","ÁGUA"]},
{"id": "omastar","dex": 139,"nome": "OMASTAR","tipos": ["PEDRA","ÁGUA"]},
{"id": "kabuto","dex": 140,"nome": "KABUTO","tipos": ["PEDRA","ÁGUA"]},
{"id": "kabutops","dex": 141,"nome": "KABUTOPS","tipos": ["PEDRA","ÁGUA"]},
{"id": "aerodactyl","dex": 142,"nome": "AERODACTYL","tipos": ["PEDRA","VOADOR"]},
{"id": "snorlax","dex": 143,"nome": "SNORLAX","tipos": ["NORMAL"]},
{"id": "articuno","dex": 144,"nome": "ARTICUNO","tipos": ["GELO","VOADOR"]},
{"id": "zapdos","dex": 145,"nome": "ZAPDOS","tipos": ["ELÉTRICO","VOADOR"]},
{"id": "moltres","dex": 146,"nome": "MOLTRES","tipos": ["FOGO","VOADOR"]},
{"id": "dratini","dex": 147,"nome": "DRATINI","tipos": ["DRAGÃO"]},
{"id": "dragonair","dex": 148,"nome": "DRAGONAIR","tipos": ["DRAGÃO"]},
{"id": "dragonite","dex": 149,"nome": "DRAGONITE","tipos": ["DRAGÃO","VOADOR"]},
{"id": "mewtwo","dex": 150,"nome": "MEWTWO","tipos": ["PSÍQUICO"]},
{"id": "mew","dex": 151,"nome": "MEW","tipos": ["PSÍQUICO"]},
{"id": "sentret","dex": 161,"nome": "SENTRET","tipos": ["NORMAL"]},
{"id": "ledyba","dex": 165,"nome": "LEDYBA","tipos": ["INSETO","VOADOR"]},
{"id": "spinarak","dex": 167,"nome": "SPINARAK","tipos": ["INSETO","VENENO"]},
{"id": "natu","dex": 177,"nome": "NATU","tipos": ["PSÍQUICO","VOADOR"]},
{"id": "marill","dex": 183,"nome": "MARILL","tipos": ["ÁGUA","FADA"]},
{"id": "hoppip","dex": 187,"nome": "HOPPIP","tipos": ["PLANTA","VOADOR"]},
{"id": "yanma","dex": 193,"nome": "YANMA","tipos": ["INSETO","VOADOR"]},
{"id": "misdreavus","dex": 200,"nome": "MISDREAVUS","tipos": ["FANTASMA"]},
{"id": "wobbuffet","dex": 202,"nome": "WOBBUFFET","tipos": ["PSÍQUICO"]},
{"id": "dunsparce","dex": 206,"nome": "DUNSPARCE","tipos": ["NORMAL"]},
{"id": "heracross","dex": 214,"nome": "HERACROSS","tipos": ["INSETO","LUTADOR"]},
{"id": "phanpy","dex": 231,"nome": "PHANPY","tipos": ["TERRA"]},
{"id": "larvitar","dex": 246,"nome": "LARVITAR","tipos": ["PEDRA","TERRA"]},
{"id": "furret","dex": 162,"nome": "FURRET","tipos": ["NORMAL"]},
{"id": "ledian","dex": 166,"nome": "LEDIAN","tipos": ["INSETO","VOADOR"]},
{"id": "ariados","dex": 168,"nome": "ARIADOS","tipos": ["INSETO","VENENO"]},
{"id": "xatu","dex": 178,"nome": "XATU","tipos": ["PSÍQUICO","VOADOR"]},
{"id": "azumarill","dex": 184,"nome": "AZUMARILL","tipos": ["ÁGUA","FADA"]},
{"id": "skiploom","dex": 188,"nome": "SKIPLOOM","tipos": ["PLANTA","VOADOR"]},
{"id": "jumpluff","dex": 189,"nome": "JUMPLUFF","tipos": ["PLANTA","VOADOR"]},
{"id": "donphan","dex": 232,"nome": "DONPHAN","tipos": ["TERRA"]},
{"id": "pupitar","dex": 247,"nome": "PUPITAR","tipos": ["PEDRA","TERRA"]},
{"id": "tyranitar","dex": 248,"nome": "TYRANITAR","tipos": ["PEDRA","SOMBRIO"]},
{"id": "mismagius","dex": 429,"nome": "MISMAGIUS","tipos": ["FANTASMA"]},
{"id": "yanmega","dex": 469,"nome": "YANMEGA","tipos": ["INSETO","VOADOR"]},
{"id": "dudunsparce","dex": 982,"nome": "DUDUNSPARCE","tipos": ["NORMAL"]},
{"id": "sneasel","dex": 215,"nome": "SNEASEL","tipos": ["SOMBRIO","GELO"]},
{"id": "weavile","dex": 461,"nome": "WEAVILE","tipos": ["SOMBRIO","GELO"]},
{"id": "slugma","dex": 218,"nome": "SLUGMA","tipos": ["FOGO"]},
{"id": "magcargo","dex": 219,"nome": "MAGCARGO","tipos": ["FOGO","PEDRA"]},
{"id": "swinub","dex": 220,"nome": "SWINUB","tipos": ["GELO","TERRA"]},
{"id": "piloswine","dex": 221,"nome": "PILOSWINE","tipos": ["GELO","TERRA"]},
{"id": "mamoswine","dex": 473,"nome": "MAMOSWINE","tipos": ["GELO","TERRA"]},
{"id": "porygon2","dex": 233,"nome": "PORYGON2","tipos": ["NORMAL"]},
{"id": "porygonz","dex": 474,"nome": "PORYGON-Z","tipos": ["NORMAL"]},
{"id": "cranidos","dex": 408,"nome": "CRANIDOS","tipos": ["PEDRA"]},
{"id": "rampardos","dex": 409,"nome": "RAMPARDOS","tipos": ["PEDRA"]},
{"id": "shieldon","dex": 410,"nome": "SHIELDON","tipos": ["PEDRA","AÇO"]},
{"id": "bastiodon","dex": 411,"nome": "BASTIODON","tipos": ["PEDRA","AÇO"]},
{"id": "lileep","dex": 345,"nome": "LILEEP","tipos": ["PEDRA","PLANTA"]},
{"id": "anorith","dex": 347,"nome": "ANORITH","tipos": ["PEDRA","INSETO"]},
{"id": "tirtouga","dex": 564,"nome": "TIRTOUGA","tipos": ["ÁGUA","PEDRA"]},
{"id": "archen","dex": 566,"nome": "ARCHEN","tipos": ["PEDRA","VOADOR"]},
{"id": "dracozolt","dex": 880,"nome": "DRACOZOLT","tipos": ["ELÉTRICO","DRAGÃO"]},
{"id": "dracovish","dex": 882,"nome": "DRACOVISH","tipos": ["ÁGUA","DRAGÃO"]},
{"id": "unown","dex": 201,"nome": "UNOWN","tipos": ["PSÍQUICO"]},
{"id": "shedinja","dex": 292,"nome": "SHEDINJA","tipos": ["INSETO","FANTASMA"]},
{"id": "rotom","dex": 479,"nome": "ROTOM","tipos": ["ELÉTRICO","FANTASMA"]},
{"id": "bronzor","dex": 436,"nome": "BRONZOR","tipos": ["AÇO","PSÍQUICO"]},
{"id": "klink","dex": 599,"nome": "KLINK","tipos": ["AÇO"]},
{"id": "cryogonal","dex": 615,"nome": "CRYOGONAL","tipos": ["GELO"]},
{"id": "golett","dex": 622,"nome": "GOLETT","tipos": ["TERRA","FANTASMA"]},
{"id": "lunatone","dex": 337,"nome": "LUNATONE","tipos": ["PEDRA","PSÍQUICO"]},
{"id": "solrock","dex": 338,"nome": "SOLROCK","tipos": ["PEDRA","PSÍQUICO"]},
{"id": "kyogre","dex": 382,"nome": "KYOGRE","tipos": ["ÁGUA"]},
{"id": "groudon","dex": 383,"nome": "GROUDON","tipos": ["TERRA"]},
{"id": "rayquaza","dex": 384,"nome": "RAYQUAZA","tipos": ["DRAGÃO","VOADOR"]},
{"id": "deoxys","dex": 386,"nome": "DEOXYS","tipos": ["PSÍQUICO"]},
{"id": "arctozolt","dex": 881,"nome": "ARCTOZOLT","tipos": ["ELÉTRICO","GELO"]},
{"id": "arctovish","dex": 883,"nome": "ARCTOVISH","tipos": ["ÁGUA","GELO"]},
{"id": "litwick","dex": 607,"nome": "LITWICK","tipos": ["FANTASMA","FOGO"]},
{"id": "lampent","dex": 608,"nome": "LAMPENT","tipos": ["FANTASMA","FOGO"]},
{"id": "chandelure","dex": 609,"nome": "CHANDELURE","tipos": ["FANTASMA","FOGO"]},
{"id": "elgyem","dex": 605,"nome": "ELGYEM","tipos": ["PSÍQUICO"]},
{"id": "beheeyem","dex": 606,"nome": "BEHEEYEM","tipos": ["PSÍQUICO"]},
{"id": "genesect","dex": 649,"nome": "GENESECT","tipos": ["INSETO","AÇO"]},
{"id": "smeargle","dex": 235,"nome": "SMEARGLE","tipos": ["NORMAL"]},
{"id": "dialga","dex": 483,"nome": "DIALGA","tipos": ["AÇO","DRAGÃO"]},
{"id": "palkia","dex": 484,"nome": "PALKIA","tipos": ["ÁGUA","DRAGÃO"]},
{"id": "arceus","dex": 493,"nome": "ARCEUS","tipos": ["NORMAL"]},
{"id": "xerneas","dex": 716,"nome": "XERNEAS","tipos": ["FADA"]},
{"id": "yveltal","dex": 717,"nome": "YVELTAL","tipos": ["SOMBRIO","VOADOR"]},
{"id": "zygarde","dex": 718,"nome": "ZYGARDE","tipos": ["DRAGÃO","TERRA"]},
{"id": "tornadus","dex": 641,"nome": "TORNADUS","tipos": ["VOADOR"]},
{"id": "pichu","dex": 172,"nome": "PICHU","tipos": ["ELÉTRICO"]},
{"id": "cleffa","dex": 173,"nome": "CLEFFA","tipos": ["FADA"]},
{"id": "igglybuff","dex": 174,"nome": "IGGLYBUFF","tipos": ["NORMAL","FADA"]},
{"id": "smoochum","dex": 238,"nome": "SMOOCHUM","tipos": ["GELO","PSÍQUICO"]},
{"id": "elekid","dex": 239,"nome": "ELEKID","tipos": ["ELÉTRICO"]},
{"id": "magby","dex": 240,"nome": "MAGBY","tipos": ["FOGO"]},
{"id": "azurill","dex": 298,"nome": "AZURILL","tipos": ["NORMAL","FADA"]},
{"id": "wynaut","dex": 360,"nome": "WYNAUT","tipos": ["PSÍQUICO"]},
{"id": "mimejr","dex": 439,"nome": "MIME-JR.","tipos": ["PSÍQUICO","FADA"]},
{"id": "happiny","dex": 440,"nome": "HAPPINY","tipos": ["NORMAL"]},
{"id": "munchlax","dex": 446,"nome": "MUNCHLAX","tipos": ["NORMAL"]},
{"id": "thundurus","dex": 642,"nome": "THUNDURUS","tipos": ["ELÉTRICO","VOADOR"]},
{"id": "landorus","dex": 645,"nome": "LANDORUS","tipos": ["TERRA","VOADOR"]},
{"id": "deoxysataque","dex": 386,"nome": "DEOXYS-ATAQUE","tipos": ["PSÍQUICO"]},
{"id": "deoxysdefesa","dex": 386,"nome": "DEOXYS-DEFESA","tipos": ["PSÍQUICO"]},
{"id": "deoxysvelocidade","dex": 386,"nome": "DEOXYS-VELOCIDADE","tipos": ["PSÍQUICO"]},
{"id": "chikorita","dex": 152,"nome": "CHIKORITA","tipos": ["PLANTA"]},
{"id": "cyndaquil","dex": 155,"nome": "CYNDAQUIL","tipos": ["FOGO"]},
{"id": "totodile","dex": 158,"nome": "TOTODILE","tipos": ["ÁGUA"]},
{"id": "treecko","dex": 252,"nome": "TREECKO","tipos": ["PLANTA"]},
{"id": "torchic","dex": 255,"nome": "TORCHIC","tipos": ["FOGO"]},
{"id": "mudkip","dex": 258,"nome": "MUDKIP","tipos": ["ÁGUA"]},
{"id": "turtwig","dex": 387,"nome": "TURTWIG","tipos": ["PLANTA"]},
{"id": "chimchar","dex": 390,"nome": "CHIMCHAR","tipos": ["FOGO"]},
{"id": "piplup","dex": 393,"nome": "PIPLUP","tipos": ["ÁGUA"]},
{"id": "snivy","dex": 495,"nome": "SNIVY","tipos": ["PLANTA"]},
{"id": "tepig","dex": 498,"nome": "TEPIG","tipos": ["FOGO"]},
{"id": "oshawott","dex": 501,"nome": "OSHAWOTT","tipos": ["ÁGUA"]},
{"id": "chespin","dex": 650,"nome": "CHESPIN","tipos": ["PLANTA"]},
{"id": "fennekin","dex": 653,"nome": "FENNEKIN","tipos": ["FOGO"]},
{"id": "froakie","dex": 656,"nome": "FROAKIE","tipos": ["ÁGUA"]},
{"id": "rowlet","dex": 722,"nome": "ROWLET","tipos": ["PLANTA","VOADOR"]},
{"id": "litten","dex": 725,"nome": "LITTEN","tipos": ["FOGO"]},
{"id": "popplio","dex": 728,"nome": "POPPLIO","tipos": ["ÁGUA"]},
{"id": "grookey","dex": 810,"nome": "GROOKEY","tipos": ["PLANTA"]},
{"id": "scorbunny","dex": 813,"nome": "SCORBUNNY","tipos": ["FOGO"]},
{"id": "sobble","dex": 816,"nome": "SOBBLE","tipos": ["ÁGUA"]},
{"id": "sprigatito","dex": 906,"nome": "SPRIGATITO","tipos": ["PLANTA"]},
{"id": "fuecoco","dex": 909,"nome": "FUECOCO","tipos": ["FOGO"]},
{"id": "quaxly","dex": 912,"nome": "QUAXLY","tipos": ["ÁGUA"]},
{"id": "bayleef","dex": 153,"nome": "BAYLEEF","tipos": ["PLANTA"]},
{"id": "meganium","dex": 154,"nome": "MEGANIUM","tipos": ["PLANTA"]},
{"id": "quilava","dex": 156,"nome": "QUILAVA","tipos": ["FOGO"]},
{"id": "typhlosion","dex": 157,"nome": "TYPHLOSION","tipos": ["FOGO"]},
{"id": "croconaw","dex": 159,"nome": "CROCONAW","tipos": ["ÁGUA"]},
{"id": "feraligatr","dex": 160,"nome": "FERALIGATR","tipos": ["ÁGUA"]},
{"id": "grovyle","dex": 253,"nome": "GROVYLE","tipos": ["PLANTA"]},
{"id": "sceptile","dex": 254,"nome": "SCEPTILE","tipos": ["PLANTA"]},
{"id": "combusken","dex": 256,"nome": "COMBUSKEN","tipos": ["FOGO","LUTADOR"]},
{"id": "blaziken","dex": 257,"nome": "BLAZIKEN","tipos": ["FOGO","LUTADOR"]},
{"id": "marshtomp","dex": 259,"nome": "MARSHTOMP","tipos": ["ÁGUA","TERRA"]},
{"id": "swampert","dex": 260,"nome": "SWAMPERT","tipos": ["ÁGUA","TERRA"]},
{"id": "grotle","dex": 388,"nome": "GROTLE","tipos": ["PLANTA"]},
{"id": "torterra","dex": 389,"nome": "TORTERRA","tipos": ["PLANTA","TERRA"]},
{"id": "monferno","dex": 391,"nome": "MONFERNO","tipos": ["FOGO","LUTADOR"]},
{"id": "infernape","dex": 392,"nome": "INFERNAPE","tipos": ["FOGO","LUTADOR"]},
{"id": "prinplup","dex": 394,"nome": "PRINPLUP","tipos": ["ÁGUA"]},
{"id": "empoleon","dex": 395,"nome": "EMPOLEON","tipos": ["ÁGUA","AÇO"]},
{"id": "servine","dex": 496,"nome": "SERVINE","tipos": ["PLANTA"]},
{"id": "serperior","dex": 497,"nome": "SERPERIOR","tipos": ["PLANTA"]},
{"id": "pignite","dex": 499,"nome": "PIGNITE","tipos": ["FOGO","LUTADOR"]},
{"id": "emboar","dex": 500,"nome": "EMBOAR","tipos": ["FOGO","LUTADOR"]},
{"id": "dewott","dex": 502,"nome": "DEWOTT","tipos": ["ÁGUA"]},
{"id": "samurott","dex": 503,"nome": "SAMUROTT","tipos": ["ÁGUA"]},
{"id": "quilladin","dex": 651,"nome": "QUILLADIN","tipos": ["PLANTA"]},
{"id": "chesnaught","dex": 652,"nome": "CHESNAUGHT","tipos": ["PLANTA","LUTADOR"]},
{"id": "braixen","dex": 654,"nome": "BRAIXEN","tipos": ["FOGO"]},
{"id": "delphox","dex": 655,"nome": "DELPHOX","tipos": ["FOGO","PSÍQUICO"]},
{"id": "frogadier","dex": 657,"nome": "FROGADIER","tipos": ["ÁGUA"]},
{"id": "greninja","dex": 658,"nome": "GRENINJA","tipos": ["ÁGUA","SOMBRIO"]},
{"id": "dartrix","dex": 723,"nome": "DARTRIX","tipos": ["PLANTA","VOADOR"]},
{"id": "decidueye","dex": 724,"nome": "DECIDUEYE","tipos": ["PLANTA","FANTASMA"]},
{"id": "torracat","dex": 726,"nome": "TORRACAT","tipos": ["FOGO"]},
{"id": "incineroar","dex": 727,"nome": "INCINEROAR","tipos": ["FOGO","SOMBRIO"]},
{"id": "brionne","dex": 729,"nome": "BRIONNE","tipos": ["ÁGUA"]},
{"id": "primarina","dex": 730,"nome": "PRIMARINA","tipos": ["ÁGUA","FADA"]},
{"id": "thwackey","dex": 811,"nome": "THWACKEY","tipos": ["PLANTA"]},
{"id": "rillaboom","dex": 812,"nome": "RILLABOOM","tipos": ["PLANTA"]},
{"id": "raboot","dex": 814,"nome": "RABOOT","tipos": ["FOGO"]},
{"id": "cinderace","dex": 815,"nome": "CINDERACE","tipos": ["FOGO"]},
{"id": "drizzile","dex": 817,"nome": "DRIZZILE","tipos": ["ÁGUA"]},
{"id": "inteleon","dex": 818,"nome": "INTELEON","tipos": ["ÁGUA"]},
{"id": "floragato","dex": 907,"nome": "FLORAGATO","tipos": ["PLANTA"]},
{"id": "meowscarada","dex": 908,"nome": "MEOWSCARADA","tipos": ["PLANTA","SOMBRIO"]},
{"id": "crocalor","dex": 910,"nome": "CROCALOR","tipos": ["FOGO"]},
{"id": "skeledirge","dex": 911,"nome": "SKELEDIRGE","tipos": ["FOGO","FANTASMA"]},
{"id": "quaxwell","dex": 913,"nome": "QUAXWELL","tipos": ["ÁGUA"]},
{"id": "quaquaval","dex": 914,"nome": "QUAQUAVAL","tipos": ["ÁGUA","LUTADOR"]},
{"id": "celebi","dex": 251,"nome": "CELEBI","tipos": ["PSÍQUICO","PLANTA"]},
{"id": "cradily","dex": 346,"nome": "CRADILY","tipos": ["PEDRA","PLANTA"]},
{"id": "armaldo","dex": 348,"nome": "ARMALDO","tipos": ["PEDRA","INSETO"]},
{"id": "carracosta","dex": 565,"nome": "CARRACOSTA","tipos": ["ÁGUA","PEDRA"]},
{"id": "archeops","dex": 567,"nome": "ARCHEOPS","tipos": ["PEDRA","VOADOR"]},
{"id": "tyrunt","dex": 696,"nome": "TYRUNT","tipos": ["PEDRA","DRAGÃO"]},
{"id": "tyrantrum","dex": 697,"nome": "TYRANTRUM","tipos": ["PEDRA","DRAGÃO"]},
{"id": "amaura","dex": 698,"nome": "AMAURA","tipos": ["PEDRA","GELO"]},
{"id": "aurorus","dex": 699,"nome": "AURORUS","tipos": ["PEDRA","GELO"]},
{"id": "relicanth","dex": 369,"nome": "RELICANTH","tipos": ["ÁGUA","PEDRA"]},
{"id": "greattusk","dex": 984,"nome": "GREAT TUSK","tipos": ["TERRA","LUTADOR"]},
{"id": "screamtail","dex": 985,"nome": "SCREAM TAIL","tipos": ["FADA","PSÍQUICO"]},
{"id": "brutebonnet","dex": 986,"nome": "BRUTE BONNET","tipos": ["PLANTA","SOMBRIO"]},
{"id": "fluttermane","dex": 987,"nome": "FLUTTER MANE","tipos": ["FANTASMA","FADA"]},
{"id": "slitherwing","dex": 988,"nome": "SLITHER WING","tipos": ["INSETO","LUTADOR"]},
{"id": "sandyshocks","dex": 989,"nome": "SANDY SHOCKS","tipos": ["ELÉTRICO","TERRA"]},
{"id": "roaringmoon","dex": 1005,"nome": "ROARING MOON","tipos": ["DRAGÃO","SOMBRIO"]},
{"id": "walkingwake","dex": 1009,"nome": "WALKING WAKE","tipos": ["ÁGUA","DRAGÃO"]},
{"id": "gougingfire","dex": 1020,"nome": "GOUGING FIRE","tipos": ["FOGO","DRAGÃO"]},
{"id": "ragingbolt","dex": 1021,"nome": "RAGING BOLT","tipos": ["ELÉTRICO","DRAGÃO"]},
{"id": "koraidon","dex": 1007,"nome": "KORAIDON","tipos": ["LUTADOR","DRAGÃO"]},
{"id": "irontreads","dex": 990,"nome": "IRON TREADS","tipos": ["TERRA","AÇO"]},
{"id": "ironbundle","dex": 991,"nome": "IRON BUNDLE","tipos": ["GELO","ÁGUA"]},
{"id": "ironhands","dex": 992,"nome": "IRON HANDS","tipos": ["LUTADOR","ELÉTRICO"]},
{"id": "ironjugulis","dex": 993,"nome": "IRON JUGULIS","tipos": ["SOMBRIO","VOADOR"]},
{"id": "ironmoth","dex": 994,"nome": "IRON MOTH","tipos": ["FOGO","VENENO"]},
{"id": "ironthorns","dex": 995,"nome": "IRON THORNS","tipos": ["PEDRA","ELÉTRICO"]},
{"id": "ironvaliant","dex": 1006,"nome": "IRON VALIANT","tipos": ["FADA","LUTADOR"]},
{"id": "ironleaves","dex": 1010,"nome": "IRON LEAVES","tipos": ["PLANTA","PSÍQUICO"]},
{"id": "ironboulder","dex": 1022,"nome": "IRON BOULDER","tipos": ["PEDRA","PSÍQUICO"]},
{"id": "ironcrown","dex": 1023,"nome": "IRON CROWN","tipos": ["AÇO","PSÍQUICO"]},
{"id": "miraidon","dex": 1008,"nome": "MIRAIDON","tipos": ["ELÉTRICO","DRAGÃO"]},
{"id": "rattataalola","dex": 19,"nome": "RATTATA-ALOLA","tipos": ["SOMBRIO","NORMAL"],"sprite": "10091","regiao": "ALOLA"},
{"id": "raticatealola","dex": 20,"nome": "RATICATE-ALOLA","tipos": ["SOMBRIO","NORMAL"],"sprite": "10092","regiao": "ALOLA"},
{"id": "raichualola","dex": 26,"nome": "RAICHU-ALOLA","tipos": ["ELÉTRICO","PSÍQUICO"],"sprite": "10100","regiao": "ALOLA"},
{"id": "sandshrewalola","dex": 27,"nome": "SANDSHREW-ALOLA","tipos": ["GELO","AÇO"],"sprite": "10101","regiao": "ALOLA"},
{"id": "sandslashalola","dex": 28,"nome": "SANDSLASH-ALOLA","tipos": ["GELO","AÇO"],"sprite": "10102","regiao": "ALOLA"},
{"id": "vulpixalola","dex": 37,"nome": "VULPIX-ALOLA","tipos": ["GELO"],"sprite": "10103","regiao": "ALOLA"},
{"id": "ninetalesalola","dex": 38,"nome": "NINETALES-ALOLA","tipos": ["GELO","FADA"],"sprite": "10104","regiao": "ALOLA"},
{"id": "diglettalola","dex": 50,"nome": "DIGLETT-ALOLA","tipos": ["TERRA","AÇO"],"sprite": "10105","regiao": "ALOLA"},
{"id": "dugtrioalola","dex": 51,"nome": "DUGTRIO-ALOLA","tipos": ["TERRA","AÇO"],"sprite": "10106","regiao": "ALOLA"},
{"id": "meowthalola","dex": 52,"nome": "MEOWTH-ALOLA","tipos": ["SOMBRIO"],"sprite": "10107","regiao": "ALOLA"},
{"id": "persianalola","dex": 53,"nome": "PERSIAN-ALOLA","tipos": ["SOMBRIO"],"sprite": "10108","regiao": "ALOLA"},
{"id": "geodudealola","dex": 74,"nome": "GEODUDE-ALOLA","tipos": ["PEDRA","ELÉTRICO"],"sprite": "10109","regiao": "ALOLA"},
{"id": "graveleralola","dex": 75,"nome": "GRAVELER-ALOLA","tipos": ["PEDRA","ELÉTRICO"],"sprite": "10110","regiao": "ALOLA"},
{"id": "golemalola","dex": 76,"nome": "GOLEM-ALOLA","tipos": ["PEDRA","ELÉTRICO"],"sprite": "10111","regiao": "ALOLA"},
{"id": "grimeralola","dex": 88,"nome": "GRIMER-ALOLA","tipos": ["VENENO","SOMBRIO"],"sprite": "10112","regiao": "ALOLA"},
{"id": "mukalola","dex": 89,"nome": "MUK-ALOLA","tipos": ["VENENO","SOMBRIO"],"sprite": "10113","regiao": "ALOLA"},
{"id": "exeggutoralola","dex": 103,"nome": "EXEGGUTOR-ALOLA","tipos": ["PLANTA","DRAGÃO"],"sprite": "10114","regiao": "ALOLA"},
{"id": "marowakalola","dex": 105,"nome": "MAROWAK-ALOLA","tipos": ["FOGO","FANTASMA"],"sprite": "10115","regiao": "ALOLA"},
{"id": "meowthgalar","dex": 52,"nome": "MEOWTH-GALAR","tipos": ["AÇO"],"sprite": "10161","regiao": "GALAR"},
{"id": "ponytagalar","dex": 77,"nome": "PONYTA-GALAR","tipos": ["PSÍQUICO"],"sprite": "10162","regiao": "GALAR"},
{"id": "rapidashgalar","dex": 78,"nome": "RAPIDASH-GALAR","tipos": ["PSÍQUICO","FADA"],"sprite": "10163","regiao": "GALAR"},
{"id": "slowpokegalar","dex": 79,"nome": "SLOWPOKE-GALAR","tipos": ["PSÍQUICO"],"sprite": "10164","regiao": "GALAR"},
{"id": "slowbrogalar","dex": 80,"nome": "SLOWBRO-GALAR","tipos": ["VENENO","PSÍQUICO"],"sprite": "10165","regiao": "GALAR"},
{"id": "farfetchdgalar","dex": 83,"nome": "FARFETCHD-GALAR","tipos": ["LUTADOR"],"sprite": "10166","regiao": "GALAR"},
{"id": "weezinggalar","dex": 110,"nome": "WEEZING-GALAR","tipos": ["VENENO","FADA"],"sprite": "10167","regiao": "GALAR"},
{"id": "mrmimegalar","dex": 122,"nome": "MR-MIME-GALAR","tipos": ["GELO","PSÍQUICO"],"sprite": "10168","regiao": "GALAR"},
{"id": "articunogalar","dex": 144,"nome": "ARTICUNO-GALAR","tipos": ["PSÍQUICO","VOADOR"],"sprite": "10169","regiao": "GALAR"},
{"id": "zapdosgalar","dex": 145,"nome": "ZAPDOS-GALAR","tipos": ["LUTADOR","VOADOR"],"sprite": "10170","regiao": "GALAR"},
{"id": "moltresgalar","dex": 146,"nome": "MOLTRES-GALAR","tipos": ["SOMBRIO","VOADOR"],"sprite": "10171","regiao": "GALAR"},
{"id": "slowkinggalar","dex": 199,"nome": "SLOWKING-GALAR","tipos": ["VENENO","PSÍQUICO"],"sprite": "10172","regiao": "GALAR"},
{"id": "corsolagalar","dex": 222,"nome": "CORSOLA-GALAR","tipos": ["FANTASMA"],"sprite": "10173","regiao": "GALAR"},
{"id": "zigzagoongalar","dex": 263,"nome": "ZIGZAGOON-GALAR","tipos": ["SOMBRIO","NORMAL"],"sprite": "10174","regiao": "GALAR"},
{"id": "linoonegalar","dex": 264,"nome": "LINOONE-GALAR","tipos": ["SOMBRIO","NORMAL"],"sprite": "10175","regiao": "GALAR"},
{"id": "darumakagalar","dex": 554,"nome": "DARUMAKA-GALAR","tipos": ["GELO"],"sprite": "10176","regiao": "GALAR"},
{"id": "darmanitangalar","dex": 555,"nome": "DARMANITAN-GALAR","tipos": ["GELO"],"sprite": "10177","regiao": "GALAR"},
{"id": "yamaskgalar","dex": 562,"nome": "YAMASK-GALAR","tipos": ["TERRA","FANTASMA"],"sprite": "10179","regiao": "GALAR"},
{"id": "stunfiskgalar","dex": 618,"nome": "STUNFISK-GALAR","tipos": ["TERRA","AÇO"],"sprite": "10180","regiao": "GALAR"},
{"id": "obstagoon","dex": 862,"nome": "OBSTAGOON","tipos": ["SOMBRIO","NORMAL"],"regiao": "GALAR"},
{"id": "perrserker","dex": 863,"nome": "PERRSERKER","tipos": ["AÇO"],"regiao": "GALAR"},
{"id": "cursola","dex": 864,"nome": "CURSOLA","tipos": ["FANTASMA"],"regiao": "GALAR"},
{"id": "sirfetchd","dex": 865,"nome": "SIRFETCHD","tipos": ["LUTADOR"],"regiao": "GALAR"},
{"id": "mrrime","dex": 866,"nome": "MR-RIME","tipos": ["GELO","PSÍQUICO"],"regiao": "GALAR"},
{"id": "runerigus","dex": 867,"nome": "RUNERIGUS","tipos": ["TERRA","FANTASMA"],"regiao": "GALAR"},
{"id": "growlithehisui","dex": 58,"nome": "GROWLITHE-HISUI","tipos": ["FOGO","PEDRA"],"sprite": "10229","regiao": "HISUI"},
{"id": "arcaninehisui","dex": 59,"nome": "ARCANINE-HISUI","tipos": ["FOGO","PEDRA"],"sprite": "10230","regiao": "HISUI"},
{"id": "voltorbhisui","dex": 100,"nome": "VOLTORB-HISUI","tipos": ["ELÉTRICO","PLANTA"],"sprite": "10231","regiao": "HISUI"},
{"id": "electrodehisui","dex": 101,"nome": "ELECTRODE-HISUI","tipos": ["ELÉTRICO","PLANTA"],"sprite": "10232","regiao": "HISUI"},
{"id": "typhlosionhisui","dex": 157,"nome": "TYPHLOSION-HISUI","tipos": ["FOGO","FANTASMA"],"sprite": "10233","regiao": "HISUI"},
{"id": "qwilfishhisui","dex": 211,"nome": "QWILFISH-HISUI","tipos": ["SOMBRIO","VENENO"],"sprite": "10234","regiao": "HISUI"},
{"id": "sneaselhisui","dex": 215,"nome": "SNEASEL-HISUI","tipos": ["LUTADOR","VENENO"],"sprite": "10235","regiao": "HISUI"},
{"id": "samurotthisui","dex": 503,"nome": "SAMUROTT-HISUI","tipos": ["ÁGUA","SOMBRIO"],"sprite": "10236","regiao": "HISUI"},
{"id": "lilliganthisui","dex": 549,"nome": "LILLIGANT-HISUI","tipos": ["PLANTA","LUTADOR"],"sprite": "10237","regiao": "HISUI"},
{"id": "basculinhisui","dex": 550,"nome": "BASCULIN-HISUI","tipos": ["ÁGUA"],"sprite": "10247","regiao": "HISUI"},
{"id": "zoruahisui","dex": 570,"nome": "ZORUA-HISUI","tipos": ["NORMAL","FANTASMA"],"sprite": "10238","regiao": "HISUI"},
{"id": "zoroarkhisui","dex": 571,"nome": "ZOROARK-HISUI","tipos": ["NORMAL","FANTASMA"],"sprite": "10239","regiao": "HISUI"},
{"id": "braviaryhisui","dex": 628,"nome": "BRAVIARY-HISUI","tipos": ["PSÍQUICO","VOADOR"],"sprite": "10240","regiao": "HISUI"},
{"id": "sliggoohisui","dex": 705,"nome": "SLIGGOO-HISUI","tipos": ["AÇO","DRAGÃO"],"sprite": "10241","regiao": "HISUI"},
{"id": "goodrahisui","dex": 706,"nome": "GOODRA-HISUI","tipos": ["AÇO","DRAGÃO"],"sprite": "10242","regiao": "HISUI"},
{"id": "avalugghisui","dex": 713,"nome": "AVALUGG-HISUI","tipos": ["GELO","PEDRA"],"sprite": "10243","regiao": "HISUI"},
{"id": "decidueyehisui","dex": 724,"nome": "DECIDUEYE-HISUI","tipos": ["PLANTA","LUTADOR"],"sprite": "10244","regiao": "HISUI"},
{"id": "ursaluna","dex": 901,"nome": "URSALUNA","tipos": ["TERRA","NORMAL"],"regiao": "HISUI"},
{"id": "basculegion","dex": 902,"nome": "BASCULEGION","tipos": ["ÁGUA","FANTASMA"],"regiao": "HISUI"},
{"id": "sneasler","dex": 903,"nome": "SNEASLER","tipos": ["LUTADOR","VENENO"],"regiao": "HISUI"},
{"id": "overqwil","dex": 904,"nome": "OVERQWIL","tipos": ["SOMBRIO","VENENO"],"regiao": "HISUI"},
{"id": "taurospaldea","dex": 128,"nome": "TAUROS-PALDEA","tipos": ["LUTADOR"],"sprite": "10250","regiao": "PALDEA"},
{"id": "taurosbrasa","dex": 128,"nome": "TAUROS-BRASA","tipos": ["LUTADOR","FOGO"],"sprite": "10251","regiao": "PALDEA"},
{"id": "taurosonda","dex": 128,"nome": "TAUROS-ONDA","tipos": ["LUTADOR","ÁGUA"],"sprite": "10252","regiao": "PALDEA"},
{"id": "wooperpaldea","dex": 194,"nome": "WOOPER-PALDEA","tipos": ["VENENO","TERRA"],"sprite": "10253","regiao": "PALDEA"},
{"id": "ursalunapaldea","dex": 901,"nome": "URSALUNA-PALDEA","tipos": ["TERRA","NORMAL"],"sprite": "10272","regiao": "PALDEA"},
{"id": "clodsire","dex": 980,"nome": "CLODSIRE","tipos": ["VENENO","TERRA"],"regiao": "PALDEA"},
{"id": "wooper","dex": 194,"nome": "WOOPER","tipos": ["ÁGUA","TERRA"]},
{"id": "quagsire","dex": 195,"nome": "QUAGSIRE","tipos": ["ÁGUA","TERRA"]},
{"id": "qwilfish","dex": 211,"nome": "QWILFISH","tipos": ["ÁGUA","VENENO"]},
{"id": "teddyursa","dex": 216,"nome": "TEDDYURSA","tipos": ["NORMAL"]},
{"id": "ursaring","dex": 217,"nome": "URSARING","tipos": ["NORMAL"]},
{"id": "corsola","dex": 222,"nome": "CORSOLA","tipos": ["ÁGUA","PEDRA"]},
{"id": "zigzagoon","dex": 263,"nome": "ZIGZAGOON","tipos": ["NORMAL"]},
{"id": "linoone","dex": 264,"nome": "LINOONE","tipos": ["NORMAL"]},
{"id": "petilil","dex": 548,"nome": "PETILIL","tipos": ["PLANTA"]},
{"id": "lilligant","dex": 549,"nome": "LILLIGANT","tipos": ["PLANTA"]},
{"id": "basculin","dex": 550,"nome": "BASCULIN","tipos": ["ÁGUA"]},
{"id": "darumaka","dex": 554,"nome": "DARUMAKA","tipos": ["FOGO"]},
{"id": "darmanitan","dex": 555,"nome": "DARMANITAN","tipos": ["FOGO"]},
{"id": "yamask","dex": 562,"nome": "YAMASK","tipos": ["FANTASMA"]},
{"id": "cofagrigus","dex": 563,"nome": "COFAGRIGUS","tipos": ["FANTASMA"]},
{"id": "zorua","dex": 570,"nome": "ZORUA","tipos": ["SOMBRIO"]},
{"id": "zoroark","dex": 571,"nome": "ZOROARK","tipos": ["SOMBRIO"]},
{"id": "stunfisk","dex": 618,"nome": "STUNFISK","tipos": ["TERRA","ELÉTRICO"]},
{"id": "rufflet","dex": 627,"nome": "RUFFLET","tipos": ["NORMAL","VOADOR"]},
{"id": "braviary","dex": 628,"nome": "BRAVIARY","tipos": ["NORMAL","VOADOR"]},
{"id": "goomy","dex": 704,"nome": "GOOMY","tipos": ["DRAGÃO"]},
{"id": "sliggoo","dex": 705,"nome": "SLIGGOO","tipos": ["DRAGÃO"]},
{"id": "goodra","dex": 706,"nome": "GOODRA","tipos": ["DRAGÃO"]},
{"id": "bergmite","dex": 712,"nome": "BERGMITE","tipos": ["GELO"]},
{"id": "avalugg","dex": 713,"nome": "AVALUGG","tipos": ["GELO"]},
{"id": "pichukanto","dex": 172,"nome": "PICHU KANTO","tipos": ["ELÉTRICO"],"sprite": "30094","regiao": "BONÉ"},
{"id": "pikakanto","dex": 25,"nome": "PIKA KANTO","tipos": ["ELÉTRICO"],"sprite": "10094","regiao": "BONÉ"},
{"id": "raikanto","dex": 26,"nome": "RAI KANTO","tipos": ["ELÉTRICO"],"sprite": "20094","regiao": "BONÉ"},
{"id": "pichujohto","dex": 172,"nome": "PICHU JOHTO","tipos": ["ELÉTRICO"],"sprite": "30148","regiao": "BONÉ"},
{"id": "pikajohto","dex": 25,"nome": "PIKA JOHTO","tipos": ["ELÉTRICO"],"sprite": "10148","regiao": "BONÉ"},
{"id": "raijohto","dex": 26,"nome": "RAI JOHTO","tipos": ["ELÉTRICO"],"sprite": "20148","regiao": "BONÉ"},
{"id": "pichuhoenn","dex": 172,"nome": "PICHU HOENN","tipos": ["ELÉTRICO"],"sprite": "30095","regiao": "BONÉ"},
{"id": "pikahoenn","dex": 25,"nome": "PIKA HOENN","tipos": ["ELÉTRICO"],"sprite": "10095","regiao": "BONÉ"},
{"id": "raihoenn","dex": 26,"nome": "RAI HOENN","tipos": ["ELÉTRICO"],"sprite": "20095","regiao": "BONÉ"},
{"id": "pichusinnoh","dex": 172,"nome": "PICHU SINNOH","tipos": ["ELÉTRICO"],"sprite": "30096","regiao": "BONÉ"},
{"id": "pikasinnoh","dex": 25,"nome": "PIKA SINNOH","tipos": ["ELÉTRICO"],"sprite": "10096","regiao": "BONÉ"},
{"id": "raisinnoh","dex": 26,"nome": "RAI SINNOH","tipos": ["ELÉTRICO"],"sprite": "20096","regiao": "BONÉ"},
{"id": "pichuunova","dex": 172,"nome": "PICHU UNOVA","tipos": ["ELÉTRICO"],"sprite": "30097","regiao": "BONÉ"},
{"id": "pikaunova","dex": 25,"nome": "PIKA UNOVA","tipos": ["ELÉTRICO"],"sprite": "10097","regiao": "BONÉ"},
{"id": "raiunova","dex": 26,"nome": "RAI UNOVA","tipos": ["ELÉTRICO"],"sprite": "20097","regiao": "BONÉ"},
{"id": "pichukalos","dex": 172,"nome": "PICHU KALOS","tipos": ["ELÉTRICO"],"sprite": "30098","regiao": "BONÉ"},
{"id": "pikakalos","dex": 25,"nome": "PIKA KALOS","tipos": ["ELÉTRICO"],"sprite": "10098","regiao": "BONÉ"},
{"id": "raikalos","dex": 26,"nome": "RAI KALOS","tipos": ["ELÉTRICO"],"sprite": "20098","regiao": "BONÉ"},
{"id": "pichualola","dex": 172,"nome": "PICHU ALOLA","tipos": ["ELÉTRICO"],"sprite": "30099","regiao": "BONÉ"},
{"id": "pikaalola","dex": 25,"nome": "PIKA ALOLA","tipos": ["ELÉTRICO"],"sprite": "10099","regiao": "BONÉ"},
{"id": "raialola","dex": 26,"nome": "RAI ALOLA","tipos": ["ELÉTRICO","PSÍQUICO"],"sprite": "20099","regiao": "BONÉ"},
{"id": "pichugalar","dex": 172,"nome": "PICHU GALAR","tipos": ["ELÉTRICO"],"sprite": "30160","regiao": "BONÉ"},
{"id": "pikagalar","dex": 25,"nome": "PIKA GALAR","tipos": ["ELÉTRICO"],"sprite": "10160","regiao": "BONÉ"},
{"id": "raigalar","dex": 26,"nome": "RAI GALAR","tipos": ["ELÉTRICO"],"sprite": "20160","regiao": "BONÉ"},
{"id": "decamark","dex": 0,"nome": "??????????","tipos": ["GLITCH"],"sprite": "decamark"},
{"id": "missingno","dex": 0,"nome": "MISSINGNO.","tipos": ["GLITCH"]}
];
